# Node.js with webpack
# Build a Node.js project using the webpack CLI.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: 'Default'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g webpack webpack-cli --save-dev
    npm install
    npx webpack --config webpack.config.js
  displayName: 'npm install, run webpack'

- task: FortifyScanCentralDAST@7
  inputs:
    scanCentralDastApiUrl: 'https://pentester:5001/api'
    scanCentralCiCdToken: '4'
    sscCiToken: 'cac97901-cef5-4597-94f1-ff444b979646'
    TargetUrl: 'http://192.168.70.44:3000'